use classicmodels;
select customerNumber,contactLastName,contactFirstName,50000 AS salary ,50000*0.10 AS bonus , 50000+(50000*0.10) AS total_salary from customers;
select productName,buyprice,buyprice+500 AS newbuyprice from products;
select productName,buyprice,msrp,msrp-buyprice AS estimated_profit from products;
select * from products where buyprice>50;
select orderNumber from orderdetails where quantityOrdered>=40;
select customerName,country from customers where country='USA';
select customerName,country from customers where country='USA' or country='France';
select * from orderdetails where quantityOrdered>30 and priceEach>100;
select * from customers where not country='USA';
select * from customers where country IN ('USA','France','Germany');
select * from productLines where productLine IN ('Classic Cars','Motorcycles','Planes');
select * from employees where officeCode IN (1,4,7);
select * from products where buyprice between 30 and 80;
select * from orderdetails where quantityOrdered between 20 and 50;
select * from offices where officeCode between 2 and 5;
select * from customers;
select customerName from customers where customerName LIKE 'A%';
select customerName,country from customers where country LIKE '%land';
select productName from products where productName LIKE '1969%';
select * from employees where firstName LIKE 'L%';
select contactLastName from customers where contactLastName LIKE 'A____';